version: "3.9"

services:
  backend-test:
    build: ./Loopline
    container_name: nxtturn-backend-test
    env_file:
      - .env.test
    ports:
      - "9000:8000"
    command: >
      sh -c "
      python manage.py test &&
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "

